# Site settings
title: le skwi
header-img: /img/home-bg.jpg
email: cedric@skwi.fr
copyright_name: CÃ©dric Spalvieri
description: "Development is more about humans than code"
baseurl: ""
url: "http://skwi.fr"
twitter_username: le_skwi
github_username:  skwi
email_username:  cedric@skwi.fr

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
